### ISSUE TITLE
errors while running the code

### ISSUE THREAD

**Issue by rghvsomani** [truffle-box/react-box#184]
Hey !! could you help me to resolve these error occurred while running this project
error 1)
showing error for
import "truffle/Assert.sol";
import "truffle/DeployedAddresses.sol";
as Assert.sol file doesn't exists in tuffle module
2)error while running the program
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path C:\Users\DELL\Downloads\E-Certify-master\pro/package.json
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, open 'C:\Users\DELL\Downloads\E-Certify-master\pro\package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by lijie-lee** [comment]
Hey @rghvsomani. 

For the **error 2)**, maybe you should run the command, like `npm start` or `npm test`, in the directory of **C:\Users\DELL\Downloads\E-Certify-master\pro\client**, which has the **package.json** file, instead of **C:\Users\DELL\Downloads\E-Certify-master\pro**. 

I just met the same error. Hope helpful.

**Comment by cliffoo** [comment]
Hey @rghvsomani this doesn't seem to be related to the react box, as the box doesn't make use of assert. If you're still having this problem, feel free to open an issue on the [Truffle repo](https://github.com/trufflesuite/truffle) with reproduction steps so we can help you debug. Thanks!
