### ISSUE TITLE
SyntaxError: Unexpected token export

### ISSUE THREAD

**Issue by jacktang** [truffle-box/react-box#49]
Hello,

I tried add `zeppelin-solidity`(1.7.0) to the react-box and run the test cases. I modified `test/simplestorage.js` to below
```
import ether from 'zeppelin-solidity/test/helpers/ether';

var SimpleStorage = artifacts.require("./SimpleStorage.sol");

contract('SimpleStorage', function(accounts) {

  it("...should store the value 89.", function() {
    return SimpleStorage.deployed().then(function(instance) {
      simpleStorageInstance = instance;

      return simpleStorageInstance.set(89, {from: accounts[0]});
    }).then(function() {
      return simpleStorageInstance.get.call();
    }).then(function(storedData) {
      assert.equal(storedData, 89, "The value 89 was not stored.");
    });
  });

});

```

When I run the `truffle test` command, it throws `Unexpected token export` error
```
11:31 $ truffle test test/simplestorage.js
Using network 'development'.

/Users/jacktang/Code/genome_block/node_modules/zeppelin-solidity/test/helpers/ether.js:1
(function (exports, require, module, __filename, __dirname) { export default function ether (n) {
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:74:10)
    at Object.runInThisContext (vm.js:116:10)
    at Module._compile (module.js:537:28)
    at Module._extensions..js (module.js:584:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/jacktang/Code/genome_block/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
```
How can I fix this?

**Comment by jacktang** [comment]
I have added 
```
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.18.0",
    "babel-preset-stage-2": "^6.18.0",
    "babel-preset-stage-3": "^6.17.0",
    "babel-register": "^6.23.0",
    "babel-preset-env": "^1.1.8",
```
into `package.json` and the `.babelrc` file
```
{
  "presets": ["env"]
}
```

**Comment by atulkc** [comment]
I am seeing the same issue as well. Any updates/pointers on how to resolve this problem?

**Comment by adrianmcli** [comment]
@atulkc @kimyd 

Since this Truffle box hasn't been updated in a long time, I've made a new Truffle Box to compete with this current one. In my truffle box (https://github.com/adrianmcli/truffle-react), I have integrated Babel into the Truffle project itself.

I also personally tested the latest zeppelin-solidity library with it. You can do the following in your test with no problems:

```
import ether from 'zeppelin-solidity/test/helpers/ether';
```

I tried to make the Truffle Box account for the most popular errors in this repo's issue tracker. So I've also moved the frontend to its own separate folder, made sure React is not ejected, and also upgraded to Web3 1.0. 

Hope this helps you guys.

**Comment by svantetobias** [comment]
I'm having the same issue with Truffle 4.1.11 and openzeppelin-solidity 1.9.0. 

Tried Babel suggestion in https://github.com/trufflesuite/truffle/issues/664, but can't make it work without breaking the start/build of the react app.

Anyone got a working workaround?

**Comment by adrianmcli** [comment]
@svantetobias have you looked at my truffle box above?

**Comment by svantetobias** [comment]
@adrianmcli Thanks for sharing your work!
1. I have implemented quite a lot using the official truffle-box. I can't seem to find any way to upgrade/switch to your version, short of having to copy paste all my work over to a new unboxed dir.
2. Any reason why this is not a pull-request to the 'official' react truffle-box?

**Comment by adrianmcli** [comment]
@svantetobias 

> 1. I can't seem to find any way to upgrade/switch to your version, short of having to copy paste all my work over to a new unboxed dir.

I think the easiest way to migrate is copying and pasting your current work. Alternatively, you can read read through the code and compare what the two boxes are doing and try to replicate that inside your own project.

> 2. Any reason why this is not a pull-request to the original react truffle-box?

Yes, because they haven't merged a new PR or added a new commit to this repo for more than half a year. If I want to move the ecosystem forward, I had to take things into my own hands and that's what I did. I am in touch with the Truffle team now though, so maybe things will change soon.

Keep an eye on what's going on :) it's a rapidly changing landscape.

**Comment by svantetobias** [comment]
@adrianmcli 
Thanks for the clarification. I ended up taking the plunge and migrated to your box. Took most of the day, but the setup seems vastly simpler and quite a lot better now. Thanks a lot!
