### ISSUE TITLE
Upgrade to web3 1.0 and ES6

### ISSUE THREAD

**Issue by fredfortier** [truffle-box/react-box#53]
I started a project with this scaffold. While it works well, an older version of web3 is injected in my unit test. Also, I cannot import ES6 modules in them.

I'd expect the unit tests to be structured more like this: http://truffleframework.com/docs/getting_started/solidity-tests

How would I attempt to upgrade my project? I tried upgraded to ES6 like this: https://ethereum.stackexchange.com/questions/21210/syntaxerror-unexpected-token-import-on-truffle-test. However, this seems to cause some conflict in the Dapp with React expecting a different Babel config.

**Comment by adrianmcli** [comment]
@fredfortier @FabiolaBusch 

Check out my alternative truffle box: https://github.com/adrianmcli/truffle-react

I use Web3 v1.0, and I have also enabled ES6 modules for writing tests. It seems like this repo is no longer actively maintained, but I tend to keep my repos pretty fresh (I am also the author of Truffle-Next btw).

I also avoid having conflicting environments between Truffle's JS environment and the React app by completely separating them. The React app resides in its own `/client` folder and the rest of the stuff is Truffle stuff. Ideally, you'd use a monorepo-like approach but the current Truffle Unbox implementation would not allow for that. See this issue I made here: https://github.com/trufflesuite/truffle-box/issues/11

**Comment by medoror** [comment]
@adrianmcli I just wanted to say that your truffle box helped me out a lot.  Great work

**Comment by adrianmcli** [comment]
@medoror thanks! always good to hear that I'm helping. The maintainers of this repo seem to have decided to move on from this Truffle Box. They're putting all their effort into Drizzle, but I'm not sure it's the right direction for our community.

**Comment by fredfortier** [comment]
@adrianmcli what's the difference between `truffle-react` and `truffle-next`? I see that you are maintaining both and that they perform the same function. Is `truffle-react` more ligthweight?

**Comment by adrianmcli** [comment]
@fredfortier 

`truffle-react` uses [Create React App](https://github.com/facebook/create-react-app) for the frontend client. `truffle-next` uses [Next.js](https://github.com/zeit/next.js/tree/canary/examples/with-reasonml) for the frontend client instead. Both of them allow you to make React web apps with minimal configuration.

Whether or not one is more lightweight than the other depends on what you are trying to do. Create React App tries to do less for you out of the box, but the generated project often have more files than a Next.js app.

The reason I maintain both is because I use both in my daily life. Both are capable of very complex web apps, but depending on your goals, usually one can get the balling rolling faster than the other. I highly recommend you check out both projects (CRA and Next.js) as they are maintained by some of the best people in the Javascript community.

**Comment by adrianmcli** [comment]
An update for you all.

I have joined the Truffle team and I will be updating and maintaining the official Truffle boxes. Don't worry guys, it's coming soon!

**Comment by adrianmcli** [comment]
This should be fixed now!
